//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ParametriaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCuentaDto", Namespace="Service.Core.DataContracts.DTO.Output")]
    [System.SerializableAttribute()]
    public partial class TipoCuentaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BancoDto", Namespace="Service.Core.DataContracts.DTO.Output")]
    [System.SerializableAttribute()]
    public partial class BancoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoMontoDto", Namespace="Service.Core.DataContracts.DTO.Output")]
    [System.SerializableAttribute()]
    public partial class TipoMontoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAdhesionDto", Namespace="Service.Core.DataContracts.DTO.Output")]
    [System.SerializableAttribute()]
    public partial class TipoAdhesionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumentoDto", Namespace="Service.Core.DataContracts.DTO.Output")]
    [System.SerializableAttribute()]
    public partial class TipoDocumentoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModuloDto", Namespace="Service.Core.DataContracts.DTO.Output")]
    [System.SerializableAttribute()]
    public partial class ModuloDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="atb_abm_tablaDto", Namespace="Service.Core.DataContracts.DTO.Output")]
    [System.SerializableAttribute()]
    public partial class atb_abm_tablaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moduloCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool permiteAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool permiteBajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tablaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moduloCodigo {
            get {
                return this.moduloCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.moduloCodigoField, value) != true)) {
                    this.moduloCodigoField = value;
                    this.RaisePropertyChanged("moduloCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool permiteAlta {
            get {
                return this.permiteAltaField;
            }
            set {
                if ((this.permiteAltaField.Equals(value) != true)) {
                    this.permiteAltaField = value;
                    this.RaisePropertyChanged("permiteAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool permiteBaja {
            get {
                return this.permiteBajaField;
            }
            set {
                if ((this.permiteBajaField.Equals(value) != true)) {
                    this.permiteBajaField = value;
                    this.RaisePropertyChanged("permiteBaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tabla {
            get {
                return this.tablaField;
            }
            set {
                if ((object.ReferenceEquals(this.tablaField, value) != true)) {
                    this.tablaField = value;
                    this.RaisePropertyChanged("tabla");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="acp_abm_campo", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class acp_abm_campo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal cantidadDecimalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoTablaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionFKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool esIdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int esPkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string etiquetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int longitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreTablaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool permiteEdicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pkTablaFKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tablaFKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoDatoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal cantidadDecimal {
            get {
                return this.cantidadDecimalField;
            }
            set {
                if ((this.cantidadDecimalField.Equals(value) != true)) {
                    this.cantidadDecimalField = value;
                    this.RaisePropertyChanged("cantidadDecimal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoTabla {
            get {
                return this.codigoTablaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoTablaField, value) != true)) {
                    this.codigoTablaField = value;
                    this.RaisePropertyChanged("codigoTabla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionFK {
            get {
                return this.descripcionFKField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionFKField, value) != true)) {
                    this.descripcionFKField = value;
                    this.RaisePropertyChanged("descripcionFK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool esIdentity {
            get {
                return this.esIdentityField;
            }
            set {
                if ((this.esIdentityField.Equals(value) != true)) {
                    this.esIdentityField = value;
                    this.RaisePropertyChanged("esIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int esPk {
            get {
                return this.esPkField;
            }
            set {
                if ((this.esPkField.Equals(value) != true)) {
                    this.esPkField = value;
                    this.RaisePropertyChanged("esPk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                if ((object.ReferenceEquals(this.etiquetaField, value) != true)) {
                    this.etiquetaField = value;
                    this.RaisePropertyChanged("etiqueta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int longitud {
            get {
                return this.longitudField;
            }
            set {
                if ((this.longitudField.Equals(value) != true)) {
                    this.longitudField = value;
                    this.RaisePropertyChanged("longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreCampo {
            get {
                return this.nombreCampoField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreCampoField, value) != true)) {
                    this.nombreCampoField = value;
                    this.RaisePropertyChanged("nombreCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreTabla {
            get {
                return this.nombreTablaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreTablaField, value) != true)) {
                    this.nombreTablaField = value;
                    this.RaisePropertyChanged("nombreTabla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool permiteEdicion {
            get {
                return this.permiteEdicionField;
            }
            set {
                if ((this.permiteEdicionField.Equals(value) != true)) {
                    this.permiteEdicionField = value;
                    this.RaisePropertyChanged("permiteEdicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pkTablaFK {
            get {
                return this.pkTablaFKField;
            }
            set {
                if ((object.ReferenceEquals(this.pkTablaFKField, value) != true)) {
                    this.pkTablaFKField = value;
                    this.RaisePropertyChanged("pkTablaFK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tablaFK {
            get {
                return this.tablaFKField;
            }
            set {
                if ((object.ReferenceEquals(this.tablaFKField, value) != true)) {
                    this.tablaFKField = value;
                    this.RaisePropertyChanged("tablaFK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoDato {
            get {
                return this.tipoDatoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoDatoField, value) != true)) {
                    this.tipoDatoField = value;
                    this.RaisePropertyChanged("tipoDato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="atb_abm_tabla", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class atb_abm_tabla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moduloCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool permiteAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool permiteBajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tablaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moduloCodigo {
            get {
                return this.moduloCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.moduloCodigoField, value) != true)) {
                    this.moduloCodigoField = value;
                    this.RaisePropertyChanged("moduloCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool permiteAlta {
            get {
                return this.permiteAltaField;
            }
            set {
                if ((this.permiteAltaField.Equals(value) != true)) {
                    this.permiteAltaField = value;
                    this.RaisePropertyChanged("permiteAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool permiteBaja {
            get {
                return this.permiteBajaField;
            }
            set {
                if ((this.permiteBajaField.Equals(value) != true)) {
                    this.permiteBajaField = value;
                    this.RaisePropertyChanged("permiteBaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tabla {
            get {
                return this.tablaField;
            }
            set {
                if ((object.ReferenceEquals(this.tablaField, value) != true)) {
                    this.tablaField = value;
                    this.RaisePropertyChanged("tabla");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tablasRelacionada", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class tablasRelacionada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApplication.ParametriaService.camposTablasRelacionada> camposField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApplication.ParametriaService.camposTablasRelacionada> campos {
            get {
                return this.camposField;
            }
            set {
                if ((object.ReferenceEquals(this.camposField, value) != true)) {
                    this.camposField = value;
                    this.RaisePropertyChanged("campos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="camposTablasRelacionada", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class camposTablasRelacionada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descFKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pkFKField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descFK {
            get {
                return this.descFKField;
            }
            set {
                if ((object.ReferenceEquals(this.descFKField, value) != true)) {
                    this.descFKField = value;
                    this.RaisePropertyChanged("descFK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pkFK {
            get {
                return this.pkFKField;
            }
            set {
                if ((object.ReferenceEquals(this.pkFKField, value) != true)) {
                    this.pkFKField = value;
                    this.RaisePropertyChanged("pkFK");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbmTablaDto", Namespace="Service.Core.DataContracts.DTO.Output")]
    [System.SerializableAttribute()]
    public partial class AbmTablaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApplication.ParametriaService.acp_abm_campo> camposField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<System.Collections.Generic.Dictionary<string, object>> datosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication.ParametriaService.atb_abm_tabla tablaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApplication.ParametriaService.tablasRelacionada> tablasRelacionadasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApplication.ParametriaService.acp_abm_campo> campos {
            get {
                return this.camposField;
            }
            set {
                if ((object.ReferenceEquals(this.camposField, value) != true)) {
                    this.camposField = value;
                    this.RaisePropertyChanged("campos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Collections.Generic.Dictionary<string, object>> datos {
            get {
                return this.datosField;
            }
            set {
                if ((object.ReferenceEquals(this.datosField, value) != true)) {
                    this.datosField = value;
                    this.RaisePropertyChanged("datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication.ParametriaService.atb_abm_tabla tabla {
            get {
                return this.tablaField;
            }
            set {
                if ((object.ReferenceEquals(this.tablaField, value) != true)) {
                    this.tablaField = value;
                    this.RaisePropertyChanged("tabla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApplication.ParametriaService.tablasRelacionada> tablasRelacionadas {
            get {
                return this.tablasRelacionadasField;
            }
            set {
                if ((object.ReferenceEquals(this.tablasRelacionadasField, value) != true)) {
                    this.tablasRelacionadasField = value;
                    this.RaisePropertyChanged("tablasRelacionadas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParametriaService.IParametriaService")]
    public interface IParametriaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarTiposCuenta", ReplyAction="http://tempuri.org/IParametriaService/buscarTiposCuentaResponse")]
        System.Collections.Generic.List<WebApplication.ParametriaService.TipoCuentaDto> buscarTiposCuenta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarTiposCuenta", ReplyAction="http://tempuri.org/IParametriaService/buscarTiposCuentaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.TipoCuentaDto>> buscarTiposCuentaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarBancos", ReplyAction="http://tempuri.org/IParametriaService/buscarBancosResponse")]
        System.Collections.Generic.List<WebApplication.ParametriaService.BancoDto> buscarBancos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarBancos", ReplyAction="http://tempuri.org/IParametriaService/buscarBancosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.BancoDto>> buscarBancosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarTiposMonto", ReplyAction="http://tempuri.org/IParametriaService/buscarTiposMontoResponse")]
        System.Collections.Generic.List<WebApplication.ParametriaService.TipoMontoDto> buscarTiposMonto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarTiposMonto", ReplyAction="http://tempuri.org/IParametriaService/buscarTiposMontoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.TipoMontoDto>> buscarTiposMontoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarTiposAdhesion", ReplyAction="http://tempuri.org/IParametriaService/buscarTiposAdhesionResponse")]
        System.Collections.Generic.List<WebApplication.ParametriaService.TipoAdhesionDto> buscarTiposAdhesion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarTiposAdhesion", ReplyAction="http://tempuri.org/IParametriaService/buscarTiposAdhesionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.TipoAdhesionDto>> buscarTiposAdhesionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarTiposDocumento", ReplyAction="http://tempuri.org/IParametriaService/buscarTiposDocumentoResponse")]
        System.Collections.Generic.List<WebApplication.ParametriaService.TipoDocumentoDto> buscarTiposDocumento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarTiposDocumento", ReplyAction="http://tempuri.org/IParametriaService/buscarTiposDocumentoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.TipoDocumentoDto>> buscarTiposDocumentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarModulos", ReplyAction="http://tempuri.org/IParametriaService/buscarModulosResponse")]
        System.Collections.Generic.List<WebApplication.ParametriaService.ModuloDto> buscarModulos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarModulos", ReplyAction="http://tempuri.org/IParametriaService/buscarModulosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.ModuloDto>> buscarModulosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarTablas", ReplyAction="http://tempuri.org/IParametriaService/buscarTablasResponse")]
        System.Collections.Generic.List<WebApplication.ParametriaService.atb_abm_tablaDto> buscarTablas(string modulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/buscarTablas", ReplyAction="http://tempuri.org/IParametriaService/buscarTablasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.atb_abm_tablaDto>> buscarTablasAsync(string modulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/obtenerTablaDatos", ReplyAction="http://tempuri.org/IParametriaService/obtenerTablaDatosResponse")]
        System.Collections.Generic.List<System.Collections.Generic.Dictionary<string, object>> obtenerTablaDatos(string nameTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/obtenerTablaDatos", ReplyAction="http://tempuri.org/IParametriaService/obtenerTablaDatosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.Dictionary<string, object>>> obtenerTablaDatosAsync(string nameTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/obtenerTabla", ReplyAction="http://tempuri.org/IParametriaService/obtenerTablaResponse")]
        WebApplication.ParametriaService.AbmTablaDto obtenerTabla(string nameTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/obtenerTabla", ReplyAction="http://tempuri.org/IParametriaService/obtenerTablaResponse")]
        System.Threading.Tasks.Task<WebApplication.ParametriaService.AbmTablaDto> obtenerTablaAsync(string nameTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/obtenerCamposTabla", ReplyAction="http://tempuri.org/IParametriaService/obtenerCamposTablaResponse")]
        System.Collections.Generic.List<WebApplication.ParametriaService.acp_abm_campo> obtenerCamposTabla(string moduloCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametriaService/obtenerCamposTabla", ReplyAction="http://tempuri.org/IParametriaService/obtenerCamposTablaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.acp_abm_campo>> obtenerCamposTablaAsync(string moduloCod);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParametriaServiceChannel : WebApplication.ParametriaService.IParametriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParametriaServiceClient : System.ServiceModel.ClientBase<WebApplication.ParametriaService.IParametriaService>, WebApplication.ParametriaService.IParametriaService {
        
        public ParametriaServiceClient() {
        }
        
        public ParametriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParametriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WebApplication.ParametriaService.TipoCuentaDto> buscarTiposCuenta() {
            return base.Channel.buscarTiposCuenta();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.TipoCuentaDto>> buscarTiposCuentaAsync() {
            return base.Channel.buscarTiposCuentaAsync();
        }
        
        public System.Collections.Generic.List<WebApplication.ParametriaService.BancoDto> buscarBancos() {
            return base.Channel.buscarBancos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.BancoDto>> buscarBancosAsync() {
            return base.Channel.buscarBancosAsync();
        }
        
        public System.Collections.Generic.List<WebApplication.ParametriaService.TipoMontoDto> buscarTiposMonto() {
            return base.Channel.buscarTiposMonto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.TipoMontoDto>> buscarTiposMontoAsync() {
            return base.Channel.buscarTiposMontoAsync();
        }
        
        public System.Collections.Generic.List<WebApplication.ParametriaService.TipoAdhesionDto> buscarTiposAdhesion() {
            return base.Channel.buscarTiposAdhesion();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.TipoAdhesionDto>> buscarTiposAdhesionAsync() {
            return base.Channel.buscarTiposAdhesionAsync();
        }
        
        public System.Collections.Generic.List<WebApplication.ParametriaService.TipoDocumentoDto> buscarTiposDocumento() {
            return base.Channel.buscarTiposDocumento();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.TipoDocumentoDto>> buscarTiposDocumentoAsync() {
            return base.Channel.buscarTiposDocumentoAsync();
        }
        
        public System.Collections.Generic.List<WebApplication.ParametriaService.ModuloDto> buscarModulos() {
            return base.Channel.buscarModulos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.ModuloDto>> buscarModulosAsync() {
            return base.Channel.buscarModulosAsync();
        }
        
        public System.Collections.Generic.List<WebApplication.ParametriaService.atb_abm_tablaDto> buscarTablas(string modulo) {
            return base.Channel.buscarTablas(modulo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.atb_abm_tablaDto>> buscarTablasAsync(string modulo) {
            return base.Channel.buscarTablasAsync(modulo);
        }
        
        public System.Collections.Generic.List<System.Collections.Generic.Dictionary<string, object>> obtenerTablaDatos(string nameTable) {
            return base.Channel.obtenerTablaDatos(nameTable);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.Dictionary<string, object>>> obtenerTablaDatosAsync(string nameTable) {
            return base.Channel.obtenerTablaDatosAsync(nameTable);
        }
        
        public WebApplication.ParametriaService.AbmTablaDto obtenerTabla(string nameTable) {
            return base.Channel.obtenerTabla(nameTable);
        }
        
        public System.Threading.Tasks.Task<WebApplication.ParametriaService.AbmTablaDto> obtenerTablaAsync(string nameTable) {
            return base.Channel.obtenerTablaAsync(nameTable);
        }
        
        public System.Collections.Generic.List<WebApplication.ParametriaService.acp_abm_campo> obtenerCamposTabla(string moduloCod) {
            return base.Channel.obtenerCamposTabla(moduloCod);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplication.ParametriaService.acp_abm_campo>> obtenerCamposTablaAsync(string moduloCod) {
            return base.Channel.obtenerCamposTablaAsync(moduloCod);
        }
    }
}
